image: fedora:latest

pylint:
  script:
    - "dnf install -y \
        python3 \
        python3-lxml \
        python3-pip \
        python3-pycurl \
        python3-pyOpenSSL \
        findutils \
        make \
        time \
        which \
      "
    - make pylint_requirements
    - make pylint

mypy:
  script:
    - "dnf install -y \
        python3 \
        python3-lxml \
        python3-pip \
        python3-pycurl \
        python3-pyOpenSSL \
        git \
        make \
        tar \
        time \
        wget \
        which \
      "
    - make mypy_requirements
    - make mypy

python_tests:
  script:
    - "dnf install -y \
        python3 \
        python3-lxml \
        python3-mock \
        python3-pip \
        python3-pycurl \
        python3-pyOpenSSL \
        corosync \
        pacemaker \
        pacemaker-cli \
        fence-agents-scsi \
        fence-agents-apc \
        fence-agents-ipmilan \
        fence-virt \
        booth-site \
        "
    - python3 -m pip install concurrencytest -r requirements.txt
    - pcs_test/suite.py -v

ruby_tests:
  script:
    - "dnf install -y \
        ruby \
        ruby-devel \
        rubygem-bundler \
        rubygem-backports \
        rubygem-ethon \
        rubygem-ffi \
        rubygem-io-console \
        rubygem-json \
        rubygem-open4 \
        rubygem-rack \
        rubygem-rack-protection \
        rubygem-rack-test \
        rubygem-sinatra \
        rubygem-tilt \
        rubygem-test-unit \
        "
    - /usr/bin/ruby -I ./pcsd -I ./pcsd/test pcsd/test/test_all_suite.rb
