language: generic

sudo: required

env:
  global:
    - SRC_PATH=/src/pcs
  matrix:
    # some tests are disabled
    - DIST=centos7
      RUBY_BIN=/usr/bin/ruby
      PYTHON_TEST_ARGS=""

services:
  - docker

before_install:
  - docker build
    --build-arg src_path=$SRC_PATH
    -t $DIST
    -f test/$DIST/Dockerfile
    .

script:
  # python test suite
  - docker run $DIST $SRC_PATH/pcs/test/suite.py -v --vanilla $PYTHON_TEST_ARGS
  # ruby test suite
  - docker run $DIST $RUBY_BIN
     -I $SRC_PATH/pcsd
     -I $SRC_PATH/pcsd/test
     $SRC_PATH/pcsd/test/test_all_suite.rb
